version: '3.8'

services:
  xxz-db:
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: devadmin
      POSTGRES_PASSWORD: safe-password
      POSTGRES_DB: nest
